2024-02-25 17:25:18,535 - pyswarms.discrete.binary - INFO - Optimize for 35 iters with {'c1': 0.5, 'c2': 0.5, 'w': 0.9, 'k': 5, 'p': 2}
2024-02-25 17:33:16,201 - pyswarms.discrete.binary - INFO - Optimization finished | best cost: 0.04656, best pos: [1 1 0 ... 0 0 1]
2024-02-25 18:47:34,088 - django.request - WARNING - Not Found: /favicon.ico
2024-02-25 18:49:06,762 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/gsl/turnkey/20020520-101.gif"
2024-02-25 18:49:06,770 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/gsl/turnkey/20020520-102.gif"
2024-02-25 18:49:06,793 - django.request - WARNING - Not Found: /3D"http://63.211.81.87/images/LTCAdv/20020319-103.gif"
2024-02-25 18:49:06,794 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/gsl/turnkey/20020520-2.jpg"
2024-02-25 18:49:06,807 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/gsl7/gsl_big.gif"
2024-02-25 18:49:06,818 - django.request - WARNING - Not Found: /3D"http://63.211.81.87/images/LTCAdv/20020319-106.gif"
2024-02-25 18:49:06,826 - django.request - WARNING - Not Found: /3D"http://63.211.81.87/images/LTCAdv/20020319-109.jpg"
2024-02-25 18:49:06,837 - django.request - WARNING - Not Found: /3D"http://63.211.81.87/images/LTCAdv/20020319-102.jpg"
2024-02-25 18:49:06,845 - django.request - WARNING - Not Found: /3D"http://63.211.81.87/images/LTCAdv/20020319-112.jpg"
2024-02-25 18:49:06,865 - django.request - WARNING - Not Found: /3D"spacer.gif"
2024-02-25 18:49:06,875 - django.request - WARNING - Not Found: /3D"http://63.211.81.87/images/LTCAdv/spacer.gif"
2024-02-25 18:49:06,882 - django.request - WARNING - Not Found: /3D"http://63.211.81.87/images/LTCAdv/20020319-2.jpg"
2024-02-25 18:49:06,894 - django.request - WARNING - Not Found: /3D"http://63.211.81.87/images/LTCAdv/20020319-3.gif"
2024-02-25 18:49:06,901 - django.request - WARNING - Not Found: /3D"http://209.63.151.9/trim/
2024-02-25 18:49:07,124 - django.request - WARNING - Not Found: /3D"http://www.lordoftheringsaudio.com/images/mixed/complete.jpg"
2024-02-25 18:49:07,127 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/fairlane/20020724-101.gif"
2024-02-25 18:49:07,131 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/fairlane/20020724-105.gif"
2024-02-25 18:49:07,137 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/fairlane/20020724-1or02.jpg"
2024-02-25 18:49:07,143 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/fairlane/20020724-103.gif"
2024-02-25 18:49:07,145 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/fairlane/20020724-104.gif"
2024-02-25 18:49:07,164 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/fairlane/20020724-106.jpg"
2024-02-25 18:49:07,170 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/fairlane/20020718-4a.gif"
2024-02-25 18:49:07,181 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/fairlane/20020718-2a01.gif"
2024-02-25 18:49:07,190 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/fairlane/20020718-2a02.gif"
2024-02-25 18:49:07,198 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/fairlane/20020718-2a03.gif"
2024-02-25 18:49:07,207 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/fairlane/20020718-3.gif"
2024-02-25 18:49:07,219 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/fairlane/20020718-5.gif"
2024-02-25 18:49:07,230 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/q.gif"
2024-02-25 18:49:07,238 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/fairlane/20020718-6.gif"
2024-02-25 18:49:07,245 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/fairlane/20020718-7.gif"
2024-02-25 18:49:07,256 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/mando/annuity0814/20020814-101.gif"
2024-02-25 18:49:07,264 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/mando/annuity0814/20020814-201.gif"
2024-02-25 18:49:07,275 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/mando/annuity0814/20020814-202.gif"
2024-02-25 18:49:07,284 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/mando/annuity0814/20020814-102.jpg"
2024-02-25 18:49:07,293 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/mando/annuity0814/20020814-4.gif"
2024-02-25 18:49:07,303 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/q_gray.gif"
2024-02-25 18:49:07,340 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/ntl/20020806-101.jpg"
2024-02-25 18:49:07,347 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/ntl/20020806-102.jpg"
2024-02-25 18:49:07,350 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/ntl/20020806-103.gif"
2024-02-25 18:49:07,371 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/ntl/20020514-6c.gif"
2024-02-25 18:49:07,374 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/ntl/20020617-1.gif"
2024-02-25 18:49:07,380 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/ntl/spacer.gif"
2024-02-25 18:49:07,394 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/ntl/20020514-7.gif"
2024-02-25 18:49:07,404 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/ntl/20020514-3big.gif"
2024-02-25 18:49:07,407 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/q.gif"
2024-02-25 18:49:07,424 - django.request - WARNING - Not Found: /3D"http://iiq.us/images/ntl/20020514-4.gif"
2024-02-25 18:49:55,847 - django.request - ERROR - Internal Server Error: /TrainPSO
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\venkat\March24\SpamDetection\SpamEmailApp\views.py", line 202, in TrainPSO
    X1, Y, selector = runPSO()
ValueError: not enough values to unpack (expected 3, got 2)
2024-02-25 18:51:29,314 - django.request - ERROR - Internal Server Error: /SpamDetectionAction
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\venkat\March24\SpamDetection\SpamEmailApp\views.py", line 276, in SpamDetectionAction
    data = pd.read_csv("SpamEmailApp/static/test.csv")
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers\readers.py", line 488, in _read
    return parser.read(nrows)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers\readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas\_libs\parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas\_libs\parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2

2024-02-25 18:53:16,914 - django.request - ERROR - Internal Server Error: /SpamDetectionAction
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\venkat\March24\SpamDetection\SpamEmailApp\views.py", line 282, in SpamDetectionAction
    temp = temp.strip().lower()
AttributeError: 'numpy.ndarray' object has no attribute 'strip'
2024-02-25 18:53:17,077 - django.request - ERROR - Internal Server Error: /SpamDetectionAction
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\venkat\March24\SpamDetection\SpamEmailApp\views.py", line 282, in SpamDetectionAction
    temp = temp.strip().lower()
AttributeError: 'numpy.ndarray' object has no attribute 'strip'
2025-01-04 16:45:00,645 - django.request - WARNING - Not Found: /
2025-01-04 16:45:00,816 - django.request - WARNING - Not Found: /favicon.ico
2025-01-04 16:45:24,777 - django.request - WARNING - Not Found: /favicon.ico
2025-01-06 10:55:14,762 - django.request - WARNING - Not Found: /
2025-01-06 10:55:14,859 - django.request - WARNING - Not Found: /favicon.ico
2025-01-06 13:31:37,880 - django.request - WARNING - Not Found: /
2025-01-06 13:31:37,929 - django.request - WARNING - Not Found: /favicon.ico
2025-01-06 13:31:44,065 - django.request - WARNING - Not Found: /favicon.ico
2025-01-06 13:31:52,931 - django.request - WARNING - Not Found: /favicon.ico
2025-01-06 13:36:25,087 - django.request - WARNING - Not Found: /installHook.js.map
2025-01-06 13:36:28,473 - django.request - ERROR - Internal Server Error: /AdminLoginAction
Traceback (most recent call last):
  File "C:\Users\nvpsa\PycharmProjects\SpamEmail\.venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\nvpsa\PycharmProjects\SpamEmail\.venv\lib\site-packages\django\core\handlers\base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view SpamEmailApp.views.AdminLoginAction didn't return an HttpResponse object. It returned None instead.
2025-01-06 13:39:39,690 - django.request - WARNING - Not Found: /3D"mailto:d_lete106@lycos.co.uk
2025-01-06 13:42:03,690 - django.request - WARNING - Not Found: /3D"mailto:d_lete106@lycos.co.uk
2025-01-07 14:43:30,671 - django.request - WARNING - Not Found: /
2025-01-08 15:22:23,922 - django.request - WARNING - Not Found: /
2025-01-09 13:38:39,948 - django.request - WARNING - Not Found: /
2025-01-09 13:38:39,972 - django.request - WARNING - Not Found: /favicon.ico
2025-01-10 10:58:04,705 - django.request - WARNING - Not Found: /
2025-01-10 11:13:26,679 - django.request - WARNING - Not Found: /
2025-01-10 11:13:26,702 - django.request - WARNING - Not Found: /favicon.ico
2025-01-10 11:13:52,999 - django.request - ERROR - Internal Server Error: /SpamDetectionAction
Traceback (most recent call last):
  File "C:\Users\nvpsa\PycharmProjects\SpamEmail\.venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\nvpsa\PycharmProjects\SpamEmail\.venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\nvpsa\PycharmProjects\SpamEmail\.venv\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\nvpsa\PycharmProjects\SpamEmail\.venv\SpamDetectionHeroustic\SpamEmailApp\views.py", line 286, in SpamDetectionAction
    clean = clean[:,pso==1]  # PSO WILL SELECT IMPORTANT FEATURES WHERE VALUE IS 1
NameError: name 'pso' is not defined
2025-01-10 11:14:11,813 - django.request - WARNING - Not Found: /favicon.ico
2025-01-10 11:14:15,297 - django.request - WARNING - Not Found: /favicon.ico
